version: "3.9"

services:
  nextcloud-db:
    image: mariadb:10.11
    container_name: nextcloud-db
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    command: ["--transaction-isolation=READ-COMMITTED", "--binlog-format=ROW"]
    volumes:
      - nc_db:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 10
    networks:
      - ncnet

  nextcloud-app:
    image: nextcloud:apache
    container_name: nextcloud-app
    restart: unless-stopped
    depends_on:
      nextcloud-db:
        condition: service_healthy
    environment:
      # --- DB ---
      MYSQL_HOST: nextcloud-db
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}

      # --- Auto-install admin ---
      NEXTCLOUD_ADMIN_USER: ${NC_ADMIN_USER}
      NEXTCLOUD_ADMIN_PASSWORD: ${NC_ADMIN_PASSWORD}

      # --- Reverse proxy / trust ---
      NEXTCLOUD_TRUSTED_DOMAINS: ${NEXTCLOUD_HOST}
      TRUSTED_PROXIES: 172.16.0.0/12,172.18.0.0/16
      OVERWRITEHOST: ${NEXTCLOUD_HOST}
      OVERWRITEPROTOCOL: https
      OVERWRITECLIURL: https://${NEXTCLOUD_HOST}

      # (Optional) PHP upload limits
      PHP_MEMORY_LIMIT: 1024M
      PHP_UPLOAD_LIMIT: 1024M

    volumes:
      - nc_data:/var/www/html
    networks:
      - ncnet
      - proxy

    labels:
      # Traefik routing
      traefik.enable: "true"

      traefik.http.routers.nc.rule: Host(`${NEXTCLOUD_HOST}`)
      traefik.http.routers.nc.entrypoints: ${TRAEFIK_ENTRYPOINT}
      traefik.http.routers.nc.tls: "true"
      traefik.http.routers.nc.tls.certresolver: ${TRAEFIK_CERTRESOLVER}
      traefik.http.services.nc.loadbalancer.server.port: "80"

      # Helpful headers (HSTS, real IP, etc.)
      traefik.http.middlewares.nc-headers.headers.stsSeconds: "31536000"
      traefik.http.middlewares.nc-headers.headers.stsIncludeSubdomains: "true"
      traefik.http.middlewares.nc-headers.headers.stsPreload: "true"
      traefik.http.middlewares.nc-headers.headers.browserXSSFilter: "true"
      traefik.http.middlewares.nc-headers.headers.customRequestHeaders.X-Forwarded-Proto: "https"
      traefik.http.routers.nc.middlewares: nc-headers@docker

volumes:
  nc_db:
  nc_data:

networks:
  proxy:
    external: true
  ncnet:
    driver: bridge
