tunnel: cea596d8-647d-497a-bcf3-9dc44f7048dd
credentials-file: /etc/cloudflared/cea596d8-647d-497a-bcf3-9dc44f7048dd.json
protocol: http2

ingress:
  - hostname: nextcloud.nexusfed.dev
    service: http://traefik:80
  - service: http_status:404
