tunnel: 912fb2ef-e2ad-4770-9a8f-f5e79a166b4a
credentials-file: /etc/cloudflared/912fb2ef-e2ad-4770-9a8f-f5e79a166b4a.json
# If QUIC feels flaky/slow, uncomment the next line to force TCP:
# protocol: http2

ingress:
  - hostname: nextcloud.nexusfed.dev
    service: http://traefik:80
  - service: http_status:404
