tunnel: nextcloud
credentials-file: ~/.cloudflared/cea596d8-647d-497a-bcf3-9dc44f7048dd.json

ingress:
  - hostname: nextcloud.nexusfed.dev
    service: http://localhost:80
  - service: http_status:404